In [ ]:
import pandas as pd
import numpy as numpy
df=pd.read_csv('/content/heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [ ]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [ ]:
df.tail()


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0

In [ ]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [ ]:
df.shape

(1025, 14)

In [ ]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [ ]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
x=df.iloc[:,:-1].values
x

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]])

In [ ]:
y=df.iloc[:,-1].values
y

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
#splitting into training and  testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=30,random_state=42)
x_train

array([[59.,  1.,  2., ...,  1.,  1.,  1.],
       [51.,  0.,  2., ...,  2.,  1.,  2.],
       [48.,  1.,  1., ...,  0.,  0.,  3.],
       ...,
       [51.,  1.,  0., ...,  2.,  0.,  3.],
       [43.,  1.,  0., ...,  2.,  0.,  3.],
       [52.,  1.,  0., ...,  2.,  1.,  2.]])

In [ ]:
x_test

array([[6.20e+01, 0.00e+00, 0.00e+00, 1.24e+02, 2.09e+02, 0.00e+00,
        1.00e+00, 1.63e+02, 0.00e+00, 0.00e+00, 2.00e+00, 0.00e+00,
        2.00e+00],
       [5.30e+01, 0.00e+00, 2.00e+00, 1.28e+02, 2.16e+02, 0.00e+00,
        0.00e+00, 1.15e+02, 0.00e+00, 0.00e+00, 2.00e+00, 0.00e+00,
        0.00e+00],
       [5.50e+01, 1.00e+00, 0.00e+00, 1.60e+02, 2.89e+02, 0.00e+00,
        0.00e+00, 1.45e+02, 1.00e+00, 8.00e-01, 1.00e+00, 1.00e+00,
        3.00e+00],
       [5.00e+01, 0.00e+00, 1.00e+00, 1.20e+02, 2.44e+02, 0.00e+00,
        1.00e+00, 1.62e+02, 0.00e+00, 1.10e+00, 2.00e+00, 0.00e+00,
        2.00e+00],
       [4.80e+01, 1.00e+00, 0.00e+00, 1.30e+02, 2.56e+02, 1.00e+00,
        0.00e+00, 1.50e+02, 1.00e+00, 0.00e+00, 2.00e+00, 2.00e+00,
        3.00e+00],
       [7.40e+01, 0.00e+00, 1.00e+00, 1.20e+02, 2.69e+02, 0.00e+00,
        0.00e+00, 1.21e+02, 1.00e+00, 2.00e-01, 2.00e+00, 1.00e+00,
        2.00e+00],
       [6.40e+01, 1.00e+00, 0.00e+00, 1.20e+02, 2.46e+02, 0.00e+00,
  

In [ ]:
y_train

array([0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,

In [ ]:
y_test


array([1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0])

In [ ]:
#normalisation
#standardscalar
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss.fit(x_train)
x_train_nor=ss.transform(x_train)
x_test_nor=ss.transform(x_test)
x_train_nor


array([[ 0.5063354 ,  0.65857238,  1.01737015, ..., -0.62054568,
         0.24767929, -2.14302994],
       [-0.3736711 , -1.51843598,  1.01737015, ...,  1.00430419,
         0.24767929, -0.52518867],
       [-0.70367354,  0.65857238,  0.04960409, ..., -2.24539554,
        -0.72639539,  1.09265259],
       ...,
       [-0.3736711 ,  0.65857238, -0.91816197, ...,  1.00430419,
        -0.72639539,  1.09265259],
       [-1.2536776 ,  0.65857238, -0.91816197, ...,  1.00430419,
        -0.72639539,  1.09265259],
       [-0.26367029,  0.65857238, -0.91816197, ...,  1.00430419,
         0.24767929, -0.52518867]])

In [ ]:
x_test_nor

array([[ 0.83633783, -1.51843598, -0.91816197, -0.43351714, -0.71677439,
        -0.41967003,  0.8900395 ,  0.60231912, -0.70923984, -0.91565004,
         1.00430419, -0.72639539, -0.52518867],
       [-0.15366948, -1.51843598,  1.01737015, -0.20568164, -0.58038674,
        -0.41967003, -1.00224533, -1.48313551, -0.70923984, -0.91565004,
         1.00430419, -0.72639539, -3.7608712 ],
       [ 0.06633215,  0.65857238, -0.91816197,  1.61700232,  0.84194164,
        -0.41967003, -1.00224533, -0.17972637,  1.40996028, -0.23255966,
        -0.62054568,  0.24767929,  1.09265259],
       [-0.48367191, -1.51843598,  0.04960409, -0.66135263, -0.03483613,
        -0.41967003,  0.8900395 ,  0.55887215, -0.70923984,  0.02359923,
         1.00430419, -0.72639539, -0.52518867],
       [-0.70367354,  0.65857238, -0.91816197, -0.09176389,  0.19897128,
         2.38282445, -1.00224533,  0.03750849,  1.40996028, -0.91565004,
         1.00430419,  1.22175397,  1.09265259],
       [ 2.15634758, -1.518435

In [ ]:
#model creation
from sklearn.neighbors import KNeighborsClassifier
knn1=KNeighborsClassifier(n_neighbors=7)
knn1.fit(x_train_nor,y_train)
y_pred=knn1.predict(x_test_nor)
y_pred


array([1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1])

In [ ]:
y_test

array([1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0])

In [ ]:
#performance evaluation
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))


              precision    recall  f1-score   support

           0       0.80      0.92      0.86        13
           1       0.93      0.82      0.88        17

    accuracy                           0.87        30
   macro avg       0.87      0.87      0.87        30
weighted avg       0.88      0.87      0.87        30



In [ ]:
#acccuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.8666666666666667

In [ ]:
pred=knn1.predict(ss.transform([[3,130,75,35,3,26,0.16,35,0,0,0,0,0]]))
pred

array([1])